resources:
- name: repo
  type: git
  source:
    uri: ((git-repo))
    branch: ((git-branch))
- name: cf
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))
    skip_cert_check: true
- name: 10m
  type: time
  source: {interval: 10m}
jobs:
- name: perf-test
  plan:
  - get: 10m
    trigger: true
  - get: repo
  - task: run-jmeter
    params:
      protocol: ((protocol))
      uaa_path: ((uaa_path))
      uaa_domain: ((uaa_domain))
      username: ((username))
      password: ((password))
      client_id: ((client_id))
      client_secret: ((client_secret))
      redirect_uri: ((redirect_uri))
      uaa_port: ((uaa_port))
      uaa_token_path: ((uaa_token_path))
      uaa_login_path: ((uaa_login_path))
      uaa_logout_path: ((uaa_logout_path))
      uaa_authorize_path: ((uaa_authorize_path))
      web_ui_protocol: ((web_ui_protocol))
      web_ui_port: ((web_ui_port))
      web_ui_domain: ((web_ui_domain))
      web_ui_oauth_authorization_path: ((web_ui_oauth_authorization_path))
      web_ui_oauth2_login_path: ((web_ui_oauth2_login_path))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: justb4/jmeter
      inputs:
      -  name: repo
      outputs:
      - name: report
      run:
        path: bash
        args: 
        - -c
        - |
          set -e
          cd repo/newrelic/jmeter

          jmeter -Dlog_level.jmeter=DEBUG \
            -J protocol=${protocol} \
            -J uaa_path=${uaa_path} \
            -J uaa_domain=${uaa_domain} \
            -J username=${username} \
            -J password=${password} \
            -J client_id=${client_id} \
            -J client_secret=${client_secret} \
            -J redirect_uri=${redirect_uri} \
            -J uaa_port=${uaa_port} \
            -J uaa_token_path=${uaa_token_path} \
            -J uaa_login_path=${uaa_login_path} \
            -J uaa_logout_path=${uaa_logout_path} \
            -J uaa_authorize_path=${uaa_authorize_path} \
            -J web_ui_protocol=${web_ui_protocol} \
            -J web_ui_port=${web_ui_port} \
            -J web_ui_domain=${web_ui_domain} \
            -J web_ui_oauth_authorization_path=${web_ui_oauth_authorization_path} \
            -J web_ui_oauth2_login_path=${web_ui_oauth2_login_path} \
            -n -t pivotal-bank.jmx -l test.jtl -j jmeter.log \
            -e -o ../../../report

  - put: cf
    params:
      manifest: repo/newrelic/jmeter/manifest.yml
      path: report
      current_app_name: demo-jemeter-report

- name: generate-events
  plan:
  - get: 10m
    trigger: true
  - get: repo
  - task: run-newrelic-event-generator
    params:
      APM_ID: ((newrelic_apm_id))
      INSIGHTS_INSERT_KEY: ((newrelic_insights_insert_key))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3-jdk-8
      inputs:
      -  name: repo
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          cd repo/newrelic/newrelic-events-generator

          mvn clean package
          java -cp target/newrelic-events-generator-1.0.0.jar io.pivotal.pa.NewRelicEventsGenerator $APM_ID $INSIGHTS_INSERT_KEY